version: '3.7'

services:
  app:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
    - /Users/alastair/code/amplab/jamendo-dataset/audio-folds/0:/app/static/tracks